### ISSUE TITLE
Error al encontrar pagina Footer 

### ISSUE THREAD

**Issue by fabriziotonin** [francooluna1/news-rolling#1]
Al ingresar a cualquier noticia y luego intentar navegar la pagina a travez de uno de los links del footer (con excepción del link acerca de nosotros ) provoca un error Cannot read property '_id' of undefined 

![image](https://user-images.githubusercontent.com/51201108/98157609-5394ab80-1eb8-11eb-913c-e834490edd18.png)

**Comment by francooluna1** [comment]
Corregido!
